version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: standard
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
